server:
  port: 80

spring:
  application:
    name: cloud-comsumer-order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http:/localhost:7002/eureka/
#      defaultZone: http://localhost:7001/eureka/