server:
  port: 80

spring:
  application:
    name: cloud-comsumer-order
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0到1之间，1代表全部采集
      probability: 1

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka/,http:/localhost:7002/eureka/
      defaultZone: http://localhost:7001/eureka/