server:
  port: 80

spring:
  application:
    name: cloud-comsumer-order
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
