server:
  port: 80

spring:
  application:
    name: cloud-comsumer-order


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

feign:
  hystrix:
    #在feign中开启hystrix
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000